name: dg_demo_2

on:
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'


jobs:
  change:
    name: Change Request
    runs-on: ubuntu-latest
    environment:     
      name: demo
      url: https://github.com       
